# dotclaude-oss Funding
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [Ketikoti]

# Uncomment to add more funding options:
# patreon: username
# open_collective: username
# ko_fi: username
# buy_me_a_coffee: username
# custom: ['https://your-custom-url.com']
